import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../css/allCss.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children}: { children: React.ReactNode }) {
  return (
      <html lang="fr">
      <body>
      <div className="min-h-full">
        <main className={"bg-tendre-black"}>
          {children}
        </main>
      </div>
      </body>
      </html>
  )
}
